twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/VehicleApp/IdentityAccess/Main/Infrastructure/Delivery/Symfony/Twig': ~

when@test:
    twig:
        strict_variables: true