services:

  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false


  App\VehicleApp\Vehicle\Main\Infrastructure\Delivery\Symfony\ApiPlatform\DataProvider\Profil\Damage\DataProvider:
    class: App\VehicleApp\Vehicle\Main\Infrastructure\Delivery\Symfony\ApiPlatform\DataProvider\Profil\Damage\DataProvider
    tags: [ 'api_platform.collection_data_provider', 'api_platform.item_data_provider' ]

  App\VehicleApp\Vehicle\Main\Infrastructure\Delivery\Symfony\ApiPlatform\DataPersister\Profil\Damage\DataPersister:
    class: App\VehicleApp\Vehicle\Main\Infrastructure\Delivery\Symfony\ApiPlatform\DataPersister\Profil\Damage\DataPersister
    tags: [ 'api_platform.data_persister']

  App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\DoctrineDamageRepository:
    class: App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\DoctrineDamageRepository
    arguments:
      $entityClass: 'App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\Damage'
    calls:
      - setCriteriaBuilder: ['@App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\Query\DoctrineDamageCriteriaBuilder']  
  App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\DamageRepository: '@App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\DoctrineDamageRepository'
  
  App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\Query\DoctrineDamageCriteriaBuilder:
    class: App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\Query\DoctrineDamageCriteriaBuilder




  #Application Service
  App\VehicleApp\Vehicle\Main\Application\Query\Profil\Damage\DamageCollectionQueryHandler:
    class: App\VehicleApp\Vehicle\Main\Application\Query\Profil\Damage\DamageCollectionQueryHandler
    arguments:
      $damageRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\DamageRepository'
      $collectionTransformer: '@App\VehicleApp\Vehicle\Main\Application\Transformer\Profil\Damage\DamageCollectionTransformer'

  App\VehicleApp\Vehicles\Main\Application\Command\Profil\Damage\CreateDamageHandler:
    class: App\VehicleApp\Vehicle\Main\Application\Command\Profil\Damage\CreateDamageHandler
    arguments:
      $damageRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\DamageRepository'
      $userVehicleRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\UserVehicle\UserVehicleRepository'
      $vehicleRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Vehicle\VehicleRepository'
      $partAndServiceRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\PartAndService\PartAndServiceRepository'

  App\VehicleApp\Vehicle\Main\Application\Command\Profil\Damage\UpdateDamageHandler:
    class: App\VehicleApp\Vehicle\Main\Application\Command\Profil\Damage\UpdateDamageHandler
    arguments:
      $userRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\UserVehicle\UserVehicleRepository'
      $vehicleRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Vehicle\VehicleRepository'
      $damageRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\DamageRepository'
      $damageCoverageRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\DamageCoverage\DamageCoverageRepository'

  App\VehicleApp\Vehicle\Main\Domain\Service\Profil\Damage\DamageDestroyer:
    class: App\VehicleApp\Vehicle\Main\Domain\Service\Profil\Damage\DamageDestroyer
    arguments:
      $damageRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\DamageRepository'

  App\VehicleApp\Vehicle\Main\Application\Command\Profil\Damage\DestroyDamageHandler:
    class:  App\VehicleApp\Vehicle\Main\Application\Command\Profil\Damage\DestroyDamageHandler
    arguments:
      $damageRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\DamageRepository'
      $damageDestroyer: '@App\VehicleApp\Vehicle\Main\Domain\Service\Profil\Damage\DamageDestroyer'

  #Transformer
  App\VehicleApp\Vehicle\Main\Application\Transformer\Profil\Damage\\DamageItemTransformer:
    class: App\VehicleApp\Vehicle\Main\Application\Transformer\Profil\Damage\DamageItemTransformer
  
  App\VehicleApp\Vehicle\Main\Application\Transformer\Profil\Damage\DamageCollectionTransformer:
    class: App\VehicleApp\Vehicle\Main\Application\Transformer\Profil\Damage\DamageCollectionTransformer


  #Fixture
  App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\Fixtures\DamageFixtures:
    class: App\VehicleApp\Vehicle\Main\Infrastructure\Persistence\Doctrine\Profil\Damage\Fixtures\DamageFixtures
    arguments:
      $damageRepository: '@App\VehicleApp\Vehicle\Main\Domain\Model\Profil\Damage\DamageRepository'
    tags: [ 'doctrine.fixture.orm' ]